# Dependencies
markdown:         redcarpet
highlighter:      pygments

permalink:        pretty

title:            Fernanda Scovino
tagline:          'My blog'
description:      'Working on data about education in Brazil and cool stuff in Python. Applied mathematician by the end of the year (I hope).'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'fernandascovino'
  url:            https://twitter.com/fernandascovino

plugins:
  - jekyll-paginate
# paginate: 5
paginate:         5

# Custom vars
# version:          2.1.0
github:           https://github.com/fernandascovino

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true